export const STATUS_BAD_REQUEST = 400;
export const STATUS_UNAUTHORIZED = 401;
export const STATUS_FORBIDDEN = 403;
export const STATUS_TOO_MANY_REQUEST = 429;

export const STATUS_INTERNAL_ERROR = 500;
